version: "3.8"

networks:
 matboxdev:
  driver: bridge

services:
 matbox:
  image: matbox:latest
  depends_on: 
     - "postgres_image"
  build: 
    context: .
    dockerfile: Dockerfile
  ports: 
    - "8000:80"
  networks:
    - matboxdev

 postgres_image:
  image: postgres:latest
  ports:
     - "5432"
  restart: always
  environment: 
     POSTGRES_HOST_AUTH_METHOD: trust
  networks:
    - matboxdev
